name: Build

on:
  # run this workflow manually from the "Actions" tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025 # https://github.com/actions/runner-images/issues/11228, "Windows Server 2025 is now available"
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Run build script
        id: runBuild
        run: ./Build.ps1
        shell: pwsh -File "{0}"

      - uses: actions/upload-artifact@v4 # https://github.com/actions/upload-artifact
        with:
          name: iisexpress
          path: ./iisexpress.7z
