name: Build

on:
  # run this workflow manually from the "Actions" tab
  workflow_dispatch:

permissions:
  # explicit permissions are now recommended
  contents: read

jobs:
  build:
    runs-on: windows-2025-vs2026 # https://github.blog/changelog/2026-02-05-github-actions-early-february-2026-updates/#windows-server-2025-with-visual-studio-2026-image-now-available-for-github-hosted-runners, "Windows Server 2025 with Visual Studio 2026 image now available for GitHub-hosted runners"
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # https://github.com/actions/checkout/releases/tag/v7.0.0, 2026-06-18; see https://github.blog/security/supply-chain-security/securing-the-open-source-supply-chain-across-github/#h-what-you-can-do-today for hash rationale
        with:
          fetch-depth: 1

      - name: Run build script
        shell: pwsh
        run: |
          ./Build.ps1

      - name: Upload result
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # https://github.com/actions/upload-artifact/releases/tag/v7.0.1, 2026-04-10
        with:
          name: iisexpress
          path: ./iisexpress.7z
          if-no-files-found: error
